<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bank_list = [
            ['name' => 'No seleccionado', 'order' => 0],
            ['name' => 'Banco Bisa S.A.', 'order' => 1],
            ['name' => 'Banco Credito de Bolivia S.A.', 'order' => 2],
            ['name' => 'Banco De la Nacion Argentina', 'order' => 3],
            ['name' => 'Banco Economico S.A.', 'order' => 4],
            ['name' => 'Banco Fortaleza S.A.', 'order' => 5],
            ['name' => 'Banco Ganadero S.A.', 'order' => 6],
            ['name' => 'Banco Mercantil Santa Cruz S.A.', 'order' => 7],
            ['name' => 'Banco Nacional de Bolivia S.A.', 'order' => 8],
            ['name' => 'Banco Prodem S.A.', 'order' => 9],
            ['name' => 'Banco Pyme De la Comunidad S.A.', 'order' => 10],
            ['name' => 'Banco Pyme Ecofuturo S.A.', 'order' => 11],
            ['name' => 'BANCO REAL', 'order' => 12],
            ['name' => 'Banco Solidario', 'order' => 13],
            ['name' => 'Banco Sudamericano', 'order' => 14],
            ['name' => 'Banco Union S.A.', 'order' => 15],
            ['name' => 'BANIF', 'order' => 16],
            ['name' => 'Bank BSU Genossenschaft', 'order' => 17],
            ['name' => 'Bank Coop AG', 'order' => 18],
            ['name' => 'Bank fur Karnten', 'order' => 19],
            ['name' => 'Bank fur Tirol und Vorarlberg', 'order' => 20],
            ['name' => 'Bank Julius Bar & Co. AG', 'order' => 21],
            ['name' => 'Bank Leumi Romania', 'order' => 22],
            ['name' => 'Bank Linth LLB AG', 'order' => 23],
            ['name' => 'Bank Oberaargau AG', 'order' => 24],
            ['name' => 'Bank of Africa', 'order' => 25],
            ['name' => 'Bank of Baroda', 'order' => 26],
            ['name' => 'Bank of Ceylon', 'order' => 27],
            ['name' => 'Bank of Cyprus', 'order' => 28],
            ['name' => 'Bank of India', 'order' => 29],
            ['name' => 'Bank Of Ireland', 'order' => 30],
            ['name' => 'Bank of Rajasthan', 'order' => 31],
            ['name' => 'Banque Cantonale de Fribourg', 'order' => 32],
            ['name' => 'Banque Cantonale de Geneve', 'order' => 33],
            ['name' => 'Banque Cantonale du Jura', 'order' => 34],
            ['name' => 'Banque Cantonale du Valais', 'order' => 35],
            ['name' => 'Banque Cantonale Neuchateloise', 'order' => 36],
            ['name' => 'Banque Cantonale Vaudoise', 'order' => 37],
            ['name' => 'BARCL', 'order' => 38],
            ['name' => 'Barclays Bank', 'order' => 39],
            ['name' => 'Basellandschaftliche Kantonalbank', 'order' => 40],
            ['name' => 'Basler Kantonalbank', 'order' => 41],
            ['name' => 'BBVA', 'order' => 42],
            ['name' => 'BCAZ', 'order' => 43],
            ['name' => 'BCM(Bank of Communications)', 'order' => 44],
            ['name' => 'BCP', 'order' => 45],
            ['name' => 'BCR - Banca Comerciala Romana', 'order' => 46],
            ['name' => 'Berner Kantonalbank AG', 'order' => 47],
            ['name' => 'BES', 'order' => 48],
            ['name' => 'BEST', 'order' => 49],
            ['name' => 'BGR', 'order' => 50],
            ['name' => 'BIC', 'order' => 51],
            ['name' => 'BIESS', 'order' => 52],
            ['name' => 'BIG', 'order' => 53],
            ['name' => 'BII', 'order' => 54],
            ['name' => 'Birmingham Midshires', 'order' => 55],
            ['name' => 'Igud', 'order' => 56],
            ['name' => 'Blom Bank Egypt', 'order' => 57],
            ['name' => 'BMAIS', 'order' => 58],
            ['name' => 'BNC', 'order' => 59],
            ['name' => 'BOC(Bank of China)', 'order' => 60],
            ['name' => 'Bouwfonds', 'order' => 61],
            ['name' => 'BPG', 'order' => 62],
            ['name' => 'BPI', 'order' => 63],
            ['name' => 'BPINV', 'order' => 64],
            ['name' => 'BPN', 'order' => 65],
            ['name' => 'BRD Groupe Societe Generale', 'order' => 66],
            ['name' => 'CAGRIC', 'order' => 67],
            ['name' => 'CAIXA ECONOMICA FEDERAL', 'order' => 68],
            ['name' => 'Canara Bank', 'order' => 69],
            ['name' => 'CARDIF', 'order' => 70],
            ['name' => 'Cargills Bank Ltd', 'order' => 71],
            ['name' => 'Cassa di Risparmio di Firenze SpA', 'order' => 72],
            ['name' => 'Cassa di Risparmio di Lucca Pisa Livorno SpA', 'order' => 73],
            ['name' => 'Catholic Syrian Bank', 'order' => 74],
            ['name' => 'CCB(China Constuction Bank)', 'order' => 75],
            ['name' => 'CEB(Chian Everbright Bank)', 'order' => 76],
            ['name' => 'CEC - Casa de Economii si Consemnatiuni', 'order' => 77],
            ['name' => 'Centenary Bank', 'order' => 78],
            ['name' => 'Central Bank of India	', 'order' => 79],
            ['name' => 'Ceska sporitelna', 'order' => 80],
            ['name' => 'Ceskomoravska stavebni sporitelna', 'order' => 81],
            ['name' => 'CGD', 'order' => 82],
            ['name' => 'Che Banca!', 'order' => 83],
            ['name' => 'Cheltenham & Gloucester', 'order' => 84],
            ['name' => 'China CITIC Bank', 'order' => 85],
            ['name' => 'CIB (Industrial Bank Co.,Ltd)', 'order' => 86],
            ['name' => 'CIB Bank', 'order' => 87],
            ['name' => 'Citibank', 'order' => 88],
            ['name' => 'City Union Bank', 'order' => 89],
            ['name' => 'Clientis AG', 'order' => 90],
            ['name' => 'CMB(China Merchants Bank Ltd)', 'order' => 91],
            ['name' => 'CMBC(China Minsheng Banking Co.Ltd', 'order' => 92],
            ['name' => 'CMHB', 'order' => 93],
            ['name' => 'Cofiec', 'order' => 94],
            ['name' => 'Colmena BCSC', 'order' => 95],
            ['name' => 'Comercial de Manabi', 'order' => 96],
            ['name' => 'Commercial Bank of Ceylon PLC', 'order' => 97],
            ['name' => 'Commerzbank', 'order' => 98],
            ['name' => 'Confiar', 'order' => 99],
            ['name' => 'CONTADO', 'order' => 100],
            ['name' => 'Coop 29 de Octubre', 'order' => 101],
            ['name' => 'Coop. Ahorro y Credito A. Mag. Rural de Chuq. RL', 'order' => 102],
            ['name' => 'Coop. Ahorro y Credito A. Mons. Felix Gainza Ltda.', 'order' => 103],
            ['name' => 'Coop. de Ahorro y Credito A S Jose de Punata Ltda.', 'order' => 104],
            ['name' => 'Coop. de Ahorro y Credito A. Cat. de Tarija Ltda.', 'order' => 105],
            ['name' => 'Coop. de Ahorro y Credito A. Ed. Gran Chaco Ltda.', 'order' => 106],
            ['name' => 'Coop. de Ahorro y Credito A. El Chorolque Ltda.', 'order' => 107],
            ['name' => 'Coop. de Ahorro y Credito A. Jesus Nazareno Ltda.', 'order' => 108],
            ['name' => 'Coop. de Ahorro y Credito A. La S. Familia R.L.', 'order' => 109],
            ['name' => 'Coop. de Ahorro y Credito A. Madre y Maestra Ltda.', 'order' => 110],
            ['name' => 'Coop. de Ahorro y Credito A. Mag. Rural Ltda.', 'order' => 111],
            ['name' => 'Coop. de Ahorro y Credito A. Quillacollo Ltda.', 'order' => 112],
            ['name' => 'Coop. de Ahorro y Credito A. S Jose de Ber. Ltda.', 'order' => 113],
            ['name' => 'Coop. de Ahorro y Credito A. S Martin Porres Ltda.', 'order' => 114],
            ['name' => 'Coop. de Ahorro y Credito A. S. Carlos Borr. Ltda.', 'order' => 115],
            ['name' => 'Coop. de Ahorro y Credito A. San Antonio Ltda.', 'order' => 116],
            ['name' => 'Coop. de Ahorro y Credito A. San Joaquin Ltda.', 'order' => 117],
            ['name' => 'Coop. de Ahorro y Credito A. San Mateo Ltda.', 'order' => 118],
            ['name' => 'Coop. de Ahorro y Credito A. San Pedro Ltda.', 'order' => 119],
            ['name' => 'Coop. de Ahorro y Credito A. San Roque Ltda.', 'order' => 120],
            ['name' => 'Coop. de Ahorro y Credito Abierta Asuncion Ltda.', 'order' => 121],
            ['name' => 'Coop. de Ahorro y Credito Abierta CACEF R.L.', 'order' => 122],
            ['name' => 'Coop. de Ahorro y Credito Abierta Catedral Ltda.', 'order' => 123],
            ['name' => 'Coop. de Ahorro y Credito Abierta Comarapa Ltda.', 'order' => 124],
            ['name' => 'Coop. de Ahorro y Credito Abierta Fatima Ltda.', 'order' => 125],
            ['name' => 'Coop. de Ahorro y Credito Abierta Inca Huasi Ltda.', 'order' => 126],
            ['name' => 'Coop. de Ahorro y Credito Abierta La Merced Ltda.', 'order' => 127],
            ['name' => 'Coop. de Ahorro y Credito Abierta Loyola Ltda.', 'order' => 128],
            ['name' => 'Coop. de Ahorro y Credito Abierta Pio X Ltda.', 'order' => 129],
            ['name' => 'Coop. de Ahorro y Credito Abierta Progreso R.L.', 'order' => 130],
            ['name' => 'Coop. de Ahorro y Credito Abierta Trinidad Ltda', 'order' => 131],
            ['name' => 'Coopcentral', 'order' => 132],
            ['name' => 'Cooperativa Financiera de Antioquia', 'order' => 133],
            ['name' => 'COOPERATIVE CENTRAL BANK', 'order' => 134],
            ['name' => 'Corporation Bank', 'order' => 135],
            ['name' => 'Cotrafa Cooperativa Financiera', 'order' => 136],
            ['name' => 'Credit Europe Bank', 'order' => 137],
            ['name' => 'Credit Suisse AG', 'order' => 138],
            ['name' => 'Credito Bergamasco SpA', 'order' => 139],
            ['name' => 'CSOB', 'order' => 140],
            ['name' => 'CYPRUS DEVELOPMENT BANK', 'order' => 141],
            ['name' => 'DaeGu Bank', 'order' => 142],
            ['name' => 'Dena Bank', 'order' => 143],
            ['name' => 'Development Credit Bank', 'order' => 144],
            ['name' => 'DFCC Bank PLC', 'order' => 145],
            ['name' => 'DFCU Bank', 'order' => 146],
            ['name' => 'Dhanalakshmi Bank', 'order' => 147],
            ['name' => 'Discount', 'order' => 148],
            ['name' => 'DSB Bank', 'order' => 149],
            ['name' => 'eBanka', 'order' => 150],
            ['name' => 'EBS', 'order' => 151],
            ['name' => 'EFG Eurobank', 'order' => 152],
            ['name' => 'Egnatia Bank', 'order' => 153],
            ['name' => 'Emporiki Bank', 'order' => 154],
            ['name' => 'Entidad Financiera de Vivienda El Progreso', 'order' => 155],
            ['name' => 'Entidad Financiera de Vivienda La Primera', 'order' => 156],
            ['name' => 'Entidad Financiera de Vivienda La Promotora', 'order' => 157],
            ['name' => 'Entidad Financiera de Vivienda Paititi', 'order' => 158],
            ['name' => 'Entidad Financiera de Vivienda Pando', 'order' => 159],
            ['name' => 'Entidad Financiera de Vivienda Potosi', 'order' => 160],
            ['name' => 'Equity Bank', 'order' => 161],
            ['name' => 'Erstebank-Sparkasse', 'order' => 162],
            ['name' => 'EUROBANK CYPRUS', 'order' => 163],
            ['name' => 'Exim Bank', 'order' => 164],
            ['name' => 'Federal Bank', 'order' => 165],
            ['name' => 'Fiba Immohyp', 'order' => 166],
            ['name' => 'FINAN', 'order' => 167],
            ['name' => 'Financiera Juriscoop', 'order' => 168],
            ['name' => 'FINIB', 'order' => 169],
            ['name' => 'First Intenational', 'order' => 170],
            ['name' => 'FORTIS ASR', 'order' => 171],
            ['name' => 'Fortis Bank', 'order' => 172],
            ['name' => 'Friesland Bank', 'order' => 173],
            ['name' => 'Garanti Bank', 'order' => 174],
            ['name' => 'GDB(Guangdong Development Bank)', 'order' => 175],
            ['name' => 'GE Money Bank', 'order' => 176],
            ['name' => 'Glarner Kantonalbank', 'order' => 177],
            ['name' => 'Glarner Regionalbank', 'order' => 178],
            ['name' => 'GMAC', 'order' => 179],
            ['name' => 'Graubundner Kantonalbank', 'order' => 180],
            ['name' => 'Habib Bank Ltd', 'order' => 181],
            ['name' => 'Halifax', 'order' => 182],
            ['name' => 'HaNa Bank', 'order' => 183],
            ['name' => 'Other', 'order' => 184],
            ['name' => 'Hatton National Bank PLC', 'order' => 185],
            ['name' => 'HDFC Bank', 'order' => 186],
            ['name' => 'HELLENIC BANK', 'order' => 187],
            ['name' => 'Helm Bank', 'order' => 188],
            ['name' => 'Housing Finance Bank', 'order' => 189],
            ['name' => 'HOUSING FINANCE COOPERATION', 'order' => 190],
            ['name' => 'HSBC', 'order' => 191],
            ['name' => 'Hypo Alpe-Adria-Bank', 'order' => 192],
            ['name' => 'HYPO stavebni sporitelna', 'order' => 193],
            ['name' => 'Hypothekarbank Lenzburg AG', 'order' => 194],
            ['name' => 'Hypovereinsbank', 'order' => 195],
            ['name' => 'ICBC(Industrial and Commercial Bank of China)', 'order' => 196],
            ['name' => 'ICICI Bank', 'order' => 197],
            ['name' => 'IDBI bank', 'order' => 198],
            ['name' => 'Igud', 'order' => 199],
            ['name' => 'Indian Bank', 'order' => 200],
            ['name' => 'Indian Overseas Bank', 'order' => 201],
            ['name' => 'IndusInd Bank', 'order' => 202],
            ['name' => 'Industrial Bank of Korea', 'order' => 203],
            ['name' => 'ING', 'order' => 204],
            ['name' => 'Inst. Financiera de Desarrollo DIACONIA FRIF - IFD', 'order' => 205],
            ['name' => 'Institucion Financiera de Desarrollo CIDRE - IFD', 'order' => 206],
            ['name' => 'Institucion Financiera de Desarrollo CRECER - IFD', 'order' => 207],
            ['name' => 'Institucion Financiera de Desarrollo FONDECO - IFD', 'order' => 208],
            ['name' => 'Institucion Financiera de Desarrollo FUBODE - IFD', 'order' => 209],
            ['name' => 'Institucion Financiera de Desarrollo IDEPRO - IFD', 'order' => 210],
            ['name' => 'Institucion Financiera de Desarrollo IMPRO - IFD', 'order' => 211],
            ['name' => 'Institucion Financiera de Desarrollo PRO MUJER', 'order' => 212],
            ['name' => 'Interhyp', 'order' => 213],
            ['name' => 'ITAU', 'order' => 214],
            ['name' => 'Jammu & Kashmir Bank', 'order' => 215],
            ['name' => 'JeJu Bank', 'order' => 216],
            ['name' => 'JeonBuk Bank', 'order' => 217],
            ['name' => 'Jerusalem', 'order' => 218],
            ['name' => 'K&H Bank', 'order' => 219],
            ['name' => 'Karnataka Bank', 'order' => 220],
            ['name' => 'Karur Vysya Bank', 'order' => 221],
            ['name' => 'KBC Bank Ireland', 'order' => 222],
            ['name' => 'Kenya Commercial Bank', 'order' => 223],
            ['name' => 'Komercijalna Banka', 'order' => 224],
            ['name' => 'Komercni banka', 'order' => 225],
            ['name' => 'KookMin Bank', 'order' => 226],
            ['name' => 'KorAm Bank', 'order' => 227],
            ['name' => 'Korea development bank', 'order' => 228],
            ['name' => 'Korea Exchange Bank', 'order' => 229],
            ['name' => 'Korea federation of Commuity Credit cooperative', 'order' => 230],
            ['name' => 'Korea federation of savings banks', 'order' => 231],
            ['name' => 'Korea Post Office Bank', 'order' => 232],
            ['name' => 'Kotak Mahindra Bank', 'order' => 233],
            ['name' => 'KwangJu Bank', 'order' => 234],
            ['name' => 'KyongNam Bank', 'order' => 235],
            ['name' => 'la Caixa', 'order' => 236],
            ['name' => 'Laxmi Vilas Bank', 'order' => 237],
            ['name' => 'Mishcan', 'order' => 238],
            ['name' => 'Libra Bank', 'order' => 239],
            ['name' => 'Liechtensteinische Landesbank (Schweiz) AG', 'order' => 240],
            ['name' => 'Luzerner Kantonalbank AG', 'order' => 241],
            ['name' => 'MCB Bank Ltd', 'order' => 242],
            ['name' => 'MG', 'order' => 243],
            ['name' => 'Migros Bank AG', 'order' => 244],
            ['name' => 'Millennium Bank', 'order' => 245],
            ['name' => 'Mishcan', 'order' => 246],
            ['name' => 'Mizrahi-Tefahot', 'order' => 247],
            ['name' => 'MKB Bank', 'order' => 248],
            ['name' => 'MKB Romexterra Bank', 'order' => 249],
            ['name' => 'Modra pyramida', 'order' => 250],
            ['name' => 'Mutualista Ambato', 'order' => 251],
            ['name' => 'Mutualista Azuay', 'order' => 252],
            ['name' => 'Mutualista Imbabura', 'order' => 253],
            ['name' => 'Mutualista Pichincha', 'order' => 254],
            ['name' => 'Nainital Bank Ltd', 'order' => 255],
            ['name' => 'Nat West', 'order' => 256],
            ['name' => 'National Agricultural Cooperative Federation', 'order' => 257],
            ['name' => 'NATIONAL BANK OF GREECE (CYPRUS)', 'order' => 258],
            ['name' => 'National Credit union federation of korea', 'order' => 259],
            ['name' => 'National Development Bank PLC', 'order' => 260],
            ['name' => 'National Federation of Fisheries Cooperatives', 'order' => 261],
            ['name' => 'Nations Trust Bank PLC', 'order' => 262],
            ['name' => 'Nationwide', 'order' => 263],
            ['name' => 'NBG', 'order' => 264],
            ['name' => 'Neue Aargauer Bank AG', 'order' => 265],
            ['name' => 'Nidwaldner Kantonalbank', 'order' => 266],
            ['name' => 'Northern Rock', 'order' => 267],
            ['name' => 'Oberbank', 'order' => 268],
            ['name' => 'Obwaldner Kantonalbank', 'order' => 269],
            ['name' => 'Oriental Bank of Commerce', 'order' => 270],
            ['name' => 'Other', 'order' => 271],
            ['name' => 'OTP Bank', 'order' => 272],
            ['name' => 'Pan Asia Banking Corporation PLC', 'order' => 273],
            ['name' => 'PBOC(The Peoples Bank Of China)', 'order' => 274],
            ['name' => 'Peoples Bank', 'order' => 275],
            ['name' => 'Permanent TSB', 'order' => 276],
            ['name' => 'Piraeus Bank', 'order' => 277],
            ['name' => 'POPUL', 'order' => 278],
            ['name' => 'Porsche Bank Romania', 'order' => 279],
            ['name' => 'PostFinance', 'order' => 280],
            ['name' => 'Principality', 'order' => 281],
            ['name' => 'Privredna banka Zagreb', 'order' => 282],
            ['name' => 'ProCredit Bank', 'order' => 283],
            ['name' => 'Produbanco', 'order' => 284],
            ['name' => 'PSBC(Postal Savings Bank of China)', 'order' => 285],
            ['name' => 'Public Bank Berhad', 'order' => 286],
            ['name' => 'Punjab and Sind Bank', 'order' => 287],
            ['name' => 'Punjab National Bank', 'order' => 288],
            ['name' => 'PuSan Bank', 'order' => 289],
            ['name' => 'Rabobank', 'order' => 290],
            ['name' => 'Raghu Bank', 'order' => 291],
            ['name' => 'Raiffeisen Bank', 'order' => 292],
            ['name' => 'RBS Romania', 'order' => 293],
            ['name' => 'RCB BANK', 'order' => 294],
            ['name' => 'RE/MAX Financiele Diensten', 'order' => 295],
            ['name' => 'REAAL', 'order' => 296],
            ['name' => 'REMAX Hitelcentrum', 'order' => 297],
            ['name' => 'Repco bank', 'order' => 298],
            ['name' => 'Romanian International Bank', 'order' => 299],
            ['name' => 'Royal Bank of Scotland', 'order' => 300],
            ['name' => 'Sampath Bank PLC', 'order' => 301],
            ['name' => 'SBI Commercial and International Bank', 'order' => 302],
            ['name' => 'Schaffhauser Kantonalbank', 'order' => 303],
            ['name' => 'Schwyzer Kantonalbank', 'order' => 304],
            ['name' => 'SDB(Shenzhen Development Bank)', 'order' => 305],
            ['name' => 'Seylan Bank PLC', 'order' => 306],
            ['name' => 'ShinHan Bank', 'order' => 307],
            ['name' => 'SNS Bank', 'order' => 308],
            ['name' => 'Sonstige', 'order' => 309],
            ['name' => 'South Indian Bank Ltd', 'order' => 310],
            ['name' => 'Sparkasse', 'order' => 311],
            ['name' => 'SPDB/SPDBank(Shanghai Pudong Development Bank)', 'order' => 312],
            ['name' => 'Splitska banka', 'order' => 313],
            ['name' => 'St. Galler Kantonalbank AG', 'order' => 314],
            ['name' => 'Stanbic Bank', 'order' => 315],
            ['name' => 'Standard Chartered Bank', 'order' => 316],
            ['name' => 'State Bank of Bikaner and Jaipur', 'order' => 317],
            ['name' => 'State Bank of Hyderabad', 'order' => 318],
            ['name' => 'State Bank of India', 'order' => 319],
            ['name' => 'State Bank of Indore', 'order' => 320],
            ['name' => 'State Bank of Mysore', 'order' => 321],
            ['name' => 'State Bank of Patiala', 'order' => 322],
            ['name' => 'State Bank of Travancore', 'order' => 323],
            ['name' => 'Stavebni sporitelna Ceske sporitelny', 'order' => 324],
            ['name' => 'Syndicate Bank', 'order' => 325],
            ['name' => 'Tamil Nadu Mercantile Bank', 'order' => 326],
            ['name' => 'The export-import bank of korea', 'order' => 327],
            ['name' => 'The Hong Kong and Shanghai Banking Corporation Ltd', 'order' => 328],
            ['name' => 'Thurgauer Kantonalbank', 'order' => 329],
            ['name' => 'TOTTA', 'order' => 330],
            ['name' => 'UBI', 'order' => 331],
            ['name' => 'UBS AG', 'order' => 332],
            ['name' => 'UCI', 'order' => 333],
            ['name' => 'UCO Bank', 'order' => 334],
            ['name' => 'Ugf Banca SpA', 'order' => 335],
            ['name' => 'Ulster Bank', 'order' => 336],
            ['name' => 'Unibanco', 'order' => 337],
            ['name' => 'Union Bank of Colombo PLC', 'order' => 338],
            ['name' => 'Union Bank of India', 'order' => 339],
            ['name' => 'United Bank of India', 'order' => 340],
            ['name' => 'Urner Kantonalbank', 'order' => 341],
            ['name' => 'USB BANK', 'order' => 342],
            ['name' => 'Valiant Bank AG', 'order' => 343],
            ['name' => 'Vijaya Bank', 'order' => 344],
            ['name' => 'Volksbank', 'order' => 345],
            ['name' => 'Volksbanken', 'order' => 346],
            ['name' => 'VR Bank', 'order' => 347],
            ['name' => 'WIR Bank Genossenschaft', 'order' => 348],
            ['name' => 'WooRi Bank', 'order' => 349],
            ['name' => 'Wustenrot', 'order' => 350],
            ['name' => 'Yes Bank', 'order' => 351],
            ['name' => 'Zagrebacka banka', 'order' => 352],
            ['name' => 'Zivnobanka', 'order' => 353],
            ['name' => 'Zuger Kantonalbank', 'order' => 354],
            ['name' => 'Zurcher Kantonalbank', 'order' => 355],
            ['name' => 'Zurcher Landbank', 'order' => 356],
            ['name' => 'Ally Financial', 'order' => 357],
            ['name' => 'American Express Company', 'order' => 358],
            ['name' => 'Ameriprise Financial', 'order' => 359],
            ['name' => 'Associated Banc-Corp', 'order' => 360],
            ['name' => 'BancWest Corporation', 'order' => 361],
            ['name' => 'Bank of America Corp', 'order' => 362],
            ['name' => 'Bank of New York Mellon', 'order' => 363],
            ['name' => 'Bank One', 'order' => 364],
            ['name' => 'BBVA USA Bancshares', 'order' => 365],
            ['name' => 'BMO Financial Corp', 'order' => 366],
            ['name' => 'BOK Financial Corporation (BOKF)', 'order' => 367],
            ['name' => 'Capital One', 'order' => 368],
            ['name' => 'Charles Schwab Corporation', 'order' => 369],
            ['name' => 'Chemical Bank', 'order' => 370],
            ['name' => 'CIT Group Inc.', 'order' => 371],
            ['name' => 'Citigroup', 'order' => 372],
            ['name' => 'City National Corp', 'order' => 373],
            ['name' => 'Comerica Incorporated', 'order' => 374],
            ['name' => 'Deutsche Bank Trust Corporation', 'order' => 375],
            ['name' => 'Discover Financial Services', 'order' => 376],
            ['name' => 'E*TRADE FINANCIAL Corp', 'order' => 377],
            ['name' => 'East West Bancorp', 'order' => 378],
            ['name' => 'Fifth Third Bancor', 'order' => 379],
            ['name' => 'First Citizens BancShares', 'order' => 380],
            ['name' => 'First Horizon National Corporation', 'order' => 381],
            ['name' => 'First Niagara Financial Group', 'order' => 382],
            ['name' => 'Goldman Sachs Group', 'order' => 383],
            ['name' => 'HSBC North America Holdings', 'order' => 384],
            ['name' => 'Hudson City Bancorp', 'order' => 385],
            ['name' => 'Huntington Bancshares Incorporated', 'order' => 386],
            ['name' => 'J.P.Morgan Chase & Co', 'order' => 387],
            ['name' => 'KeyCorp', 'order' => 388],
            ['name' => 'M&T Bank Corporation', 'order' => 389],
            ['name' => 'Morgan Stanley', 'order' => 390],
            ['name' => 'New York Community Bancorp', 'order' => 391],
            ['name' => 'Northern Trust Corporation', 'order' => 392],
            ['name' => 'Peoples United Financial (PBCT)', 'order' => 393],
            ['name' => 'PNC Financial Services Group', 'order' => 394],
            ['name' => 'Popular, Inc.', 'order' => 395],
            ['name' => 'Principal Financial Group', 'order' => 396],
            ['name' => 'RBS Citizens Financial Group', 'order' => 397],
            ['name' => 'Regions Financial Corporation', 'order' => 398],
            ['name' => 'Santander Holdings USA', 'order' => 399],
            ['name' => 'State Street Corporation', 'order' => 400],
            ['name' => 'Suntrust Banks', 'order' => 401],
            ['name' => 'SVB Financial Group', 'order' => 402],
            ['name' => 'Synovus Financial Corp.', 'order' => 403],
            ['name' => 'TD Bank US Holding Company', 'order' => 404],
            ['name' => 'U.S. Bancorp', 'order' => 405],
            ['name' => 'UnionBanCal Corporation', 'order' => 406],
            ['name' => 'USAA', 'order' => 407],
            ['name' => 'Utrecht - America Holdings', 'order' => 408],
            ['name' => 'Wells Fargo & Company', 'order' => 409],
            ['name' => 'Zions Bancorporation', 'order' => 410],
        ];


        foreach($bank_list as $bank) {
            Bank::create([
                'name' => $bank['name'],
                'order' => $bank['order'],
            ]);
        }
    }
}
