<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class OptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $values = [
            ['category'=>'Gender', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.TeamStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.ReasonForInactive', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.CurrentTitle', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.DisplayTitle', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.LicenseType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'SpokenLanguages', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.MainSpecialization', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.Education', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.PreviousOccupation', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.FloorType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PaymentPeriod', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.TransactionType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ContractType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PropertyStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PropertyTypeRes', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PropertyTypeCom', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PropertyClassification', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ListingStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.RoomTypes', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PriceType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.LeaseType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.FeeType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.LandCategory', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.EnergyRating', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.EnergyRatingUnit', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.EnergyRatingCertificate', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ArchitecturalStyle', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ExteriorFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ExteriorType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.InteriorFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.GeneralFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.LocationFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.Orientation', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.Utilities', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.Views', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Timeframe', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.Title', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.profileType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.PreferredCommMethod', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.LeadSource', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.LeadStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Office.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agenda.EventType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.MarketStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'FieldStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PropertyTypeLand', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.Relation', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.CommMacroType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.ResMacroType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.LandMacroType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.ContactFormCategory', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.SortOrderListingSearch', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'BuildingDevelopmentFeaturesAmmenities', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listings.ChequeFrequency', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.MaritalStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.MotivationForTransaction', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contact.TimeframeForTransaction', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'BuyerProfileStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'BuyerMatchesStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'BuyerProfileSorting', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Tasks.Priority', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'General.UnsubscribeSurvey', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Marketing.ListingScope', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Marketing.UnsubSurvey', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Plans.PlanType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Plans.PlanStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Plans.StepType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Plans.StepStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'EmailStatuses', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Mobile.ListingClass', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Development.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cooperation.Type', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cooperation.Status', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cooperation.DeclinedReason', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'MortgageCalculatorTimeFrame', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Agent.Certification', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Office.Certification', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listings.ListingFilter', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.ListingClass', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.PropertyTimeframe', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.ListingRoomSearch', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Reports.CategoryName', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Reports.ReportName', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Reports.ReportDescription', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listings.VAT', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Marketing.Categories', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listings.PropertyPurpose', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.Status', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.Type', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.CommissionType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'NonREPAgent.Company', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.Bank', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Websites.TransactionType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.MetroStations', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Contacts.GDPRStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Website.OfficeUserTitle', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.Stratum', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Amenities.Type', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Birthday Reminder', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Training.Levels', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Training.Statuses', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.RoomClassifications', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Nationality', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Communication Types', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ContactCategory', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'AddressType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ContactDocumentUploadTypes', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ActivityType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.CompletionTimeFrame', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ConstructionType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.DesignatedLandUse', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.LandOwnership', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.HomeOwnershipAssociation', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.OfferStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.ClosingStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.GreenhouseGasEmission', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PayableBy', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'AdditionalActivityType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'TEST', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'LeadStages', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'CommSpecIndustrial', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'CommSpecLand', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'CommSpecOffice', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Farm/Ranch', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Multi-Family', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Retail', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Activity', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ActivityParticipantStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'AgentConnectStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'AgentRating_ReferenceList', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cancellation_AgentRequested', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cancellation_ClientRequested', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cancellation_OfficeClosing', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ClientIntention', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Commercial-Retail', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'CommissionType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Dashboard Time Filter', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'DesignatedLandUse', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'EDocumentStatus', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'EDocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'EmailPriority', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ESignatureProvider', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Hotel', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'iListDocumentGenerateTypes', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ImageQualityTypes', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Industrial', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Investment', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'InvitationDeclineOption', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Land', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PreFreezReportOptions', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Sale of Business', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'SignOffMode', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'SystemDocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'VideoProviderType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'VirtualRealityTourType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Warehouse', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.BuildingFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.InteriorType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.CommercialFeatures', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ElectricityConsumptionUnitOfMeasure', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'EnergyRatingUOM', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'ListingSortBy', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'MainHeatSource', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.PrivateDocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Building', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Farm', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Garage', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Office', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Pub', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Restaurant', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Store with Apt-Office', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'PropertyTypeComm.Tax House', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.GroundRentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_Office.InsuranceDocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_PriorAffiliation', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_Suffix', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_Hobby', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_MLSCode', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_DesignationAll', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_DesignationUS', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_DesignationCANADA', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_ReferralPreferences', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_StatusChangeTerminationType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_TerminationMovement', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_LTCTerminationWhy', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_LITerminationWhy', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_TerminationWhere', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'RT_Transaction.NoteCategory', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'LifeStyle', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Parking', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.ListingStandard', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Listing.AgentListingRole', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cooperation.CancelledReason', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Cooperation.ReferralResult', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transaction.RelatedIncome', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Referral.DocumentType', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Marketing.TemplteFormat', 'created_at' => now(), 'updated_at' => now()],
            ['category'=>'Transactions.CancelledReason', 'created_at' => now(), 'updated_at' => now()],

        ];

        DB::table('options')->insert($values);

        $this->command->info('Options seeded successfully.');
    }
}
